#!/bin/bash

if [ ! -f $1 ]; then
    exit 2
fi
FILE=`basename $1 .iso`
MOUNTPOINT="$HOME/Desktop/$FILE"
if [ ! -d $MOUNTPOINT ]; then
    mkdir $MOUNTPOINT
    fuseiso -p "$1" "$MOUNTPOINT"
else
    fusermount -u "$MOUNTPOINT"
    rmdir $MOUNTPOINT
fi
